<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class SampleProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Giày Nike Air Max 90',
                'slug' => 'giay-nike-air-max-90',
                'description' => 'Giày thể thao Nike Air Max 90 kinh điển với công nghệ Air cushioning thoải mái. Phù hợp cho các hoạt động hàng ngày.',
                'price' => 2990000,
                'sale_price' => 2490000,
                'category_id' => 1,
                'stock' => 25,
                'size' => '36,37,38,39,40,41,42,43',
                'color' => 'Trắng, Đen, Xám',
                'brand' => 'Nike',
                'material' => 'Da tổng hợp, Vải lưới',
                'specifications' => 'Trọng lượng: 320g, Chiều cao gót: 28mm, Công nghệ: Air cushioning',
                'rating' => 4.8,
                'reviews_count' => 156,
                'warranty' => 'Bảo hành 12 tháng toàn bộ sản phẩm, không bao gồm lỗi do sử dụng',
                'care_instructions' => 'Vệ sinh bằng khăn ẩm, tránh máy giặt, để khô tự nhiên nơi thoáng mát',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Giày Adidas Ultraboost 22',
                'slug' => 'giay-adidas-ultraboost-22',
                'description' => 'Giày chạy bộ Adidas Ultraboost 22 với công nghệ boost mới nhất. Thoải mái cho những người yêu thích chạy bộ.',
                'price' => 3290000,
                'sale_price' => 2690000,
                'category_id' => 1,
                'stock' => 18,
                'size' => '36,37,38,39,40,41,42,43,44,45',
                'color' => 'Đen, Trắng, Xanh dương',
                'brand' => 'Adidas',
                'material' => 'Vải Primeknit, Cao su',
                'specifications' => 'Trọng lượng: 290g, Chiều cao gót: 26mm, Công nghệ: Boost cushioning',
                'rating' => 4.7,
                'reviews_count' => 203,
                'warranty' => 'Bảo hành 12 tháng, không bao gồm mục mặc',
                'care_instructions' => 'Rửa nhẹ bằng tay, để khô tự nhiên, không phơi nắng trực tiếp',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Giày Puma RS-X',
                'slug' => 'giay-puma-rs-x',
                'description' => 'Giày Puma RS-X với thiết kế hiện đại và màu sắc bắt mắt. Phù hợp cho cả nam lẫn nữ.',
                'price' => 1890000,
                'sale_price' => null,
                'category_id' => 1,
                'stock' => 35,
                'size' => '35,36,37,38,39,40,41,42,43,44',
                'color' => 'Đỏ, Xám, Xanh lá',
                'brand' => 'Puma',
                'material' => 'Vải nylon, Da tổng hợp',
                'specifications' => 'Trọng lượng: 310g, Chiều cao gót: 25mm',
                'rating' => 4.5,
                'reviews_count' => 89,
                'warranty' => 'Bảo hành 6 tháng',
                'care_instructions' => 'Vệ sinh bằng nước lạnh, không dùng chất tẩy',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Giày New Balance 574',
                'slug' => 'giay-new-balance-574',
                'description' => 'Giày New Balance 574 - biểu tượng của sự thoải mái và phong cách. Dòng giày bán chạy nhất toàn thế giới.',
                'price' => 2190000,
                'sale_price' => 1890000,
                'category_id' => 1,
                'stock' => 42,
                'size' => '36,37,38,39,40,41,42,43,44,45',
                'color' => 'Trắng xanh, Đen đỏ, Xám trắng',
                'brand' => 'New Balance',
                'material' => 'Da lộn, Lưới',
                'specifications' => 'Trọng lượng: 330g, Chiều cao gót: 32mm, Công nghệ: ENCAP',
                'rating' => 4.6,
                'reviews_count' => 234,
                'warranty' => 'Bảo hành 12 tháng',
                'care_instructions' => 'Rửa bằng nước lạnh và xà phòng mềm, để khô tự nhiên',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Giày Converse Chuck Taylor All Star',
                'slug' => 'giay-converse-chuck-taylor',
                'description' => 'Giày Converse Chuck Taylor - một huyền thoại thập kỷ. Thiết kế đơn giản nhưng cực kỳ bền bỉ.',
                'price' => 890000,
                'sale_price' => null,
                'category_id' => 1,
                'stock' => 60,
                'size' => '35,36,37,38,39,40,41,42,43,44,45',
                'color' => 'Trắng, Đen, Xanh dương, Đỏ',
                'brand' => 'Converse',
                'material' => 'Vải canvas 100%',
                'specifications' => 'Trọng lượng: 280g, Chiều cao gót: 20mm',
                'rating' => 4.4,
                'reviews_count' => 421,
                'warranty' => 'Bảo hành 6 tháng',
                'care_instructions' => 'Rửa bằng tay với nước lạnh, tránh máy giặt',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Giày Vans Old Skool',
                'slug' => 'giay-vans-old-skool',
                'description' => 'Giày Vans Old Skool với dải bên cổ điển. Giày sneaker yêu thích của những người yêu skateboard.',
                'price' => 1490000,
                'sale_price' => 1290000,
                'category_id' => 1,
                'stock' => 38,
                'size' => '35,36,37,38,39,40,41,42,43,44',
                'color' => 'Đen trắng, Đỏ trắng, Xanh trắng',
                'brand' => 'Vans',
                'material' => 'Da lộn, Canvas',
                'specifications' => 'Trọng lượng: 300g, Chiều cao gót: 21mm, Thiết kế: Classic',
                'rating' => 4.5,
                'reviews_count' => 178,
                'warranty' => 'Bảo hành 6 tháng',
                'care_instructions' => 'Lau bằng khăn ẩm, tránh nước nóng',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Giày Skechers Go Walk 5',
                'slug' => 'giay-skechers-go-walk-5',
                'description' => 'Giày Skechers Go Walk 5 - thiết kế nhẹ nhàng, thoải mái cho các hoạt động hàng ngày và đi bộ.',
                'price' => 1290000,
                'sale_price' => null,
                'category_id' => 1,
                'stock' => 50,
                'size' => '36,37,38,39,40,41,42,43,44,45',
                'color' => 'Đen, Trắng, Xám',
                'brand' => 'Skechers',
                'material' => 'Vải mesh, Foam',
                'specifications' => 'Trọng lượng: 220g, Chiều cao gót: 18mm, Công nghệ: Memory Foam',
                'rating' => 4.3,
                'reviews_count' => 145,
                'warranty' => 'Bảo hành 6 tháng',
                'care_instructions' => 'Rửa bằng nước lạnh nhẹ nhàng',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Giày ASICS Gel-Lyte III',
                'slug' => 'giay-asics-gel-lyte-iii',
                'description' => 'Giày ASICS Gel-Lyte III với công nghệ Gel cushioning tiên tiến. Lựa chọn tuyệt vời cho những người chạy bộ chuyên nghiệp.',
                'price' => 2690000,
                'sale_price' => 2290000,
                'category_id' => 1,
                'stock' => 22,
                'size' => '36,37,38,39,40,41,42,43,44,45',
                'color' => 'Đen xám, Xanh trắng, Đỏ đen',
                'brand' => 'ASICS',
                'material' => 'Da lộn, Lưới',
                'specifications' => 'Trọng lượng: 310g, Chiều cao gót: 24mm, Công nghệ: Gel cushioning',
                'rating' => 4.7,
                'reviews_count' => 167,
                'warranty' => 'Bảo hành 12 tháng',
                'care_instructions' => 'Vệ sinh nhẹ nhàng, để khô tự nhiên',
                'is_featured' => true,
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
